import { ClickablePoint } from "../Types/points";

const points : ClickablePoint[]  = [
    {
        loc: "",
        lat: 32.1656,
        lng: -82.9001,
        size: 0.1,
        color: "rgba(255, 165, 0, 0.75)",
        description: {
          title: "The Ridge",
          fullLoc: "Georgia, USA",
          year: 1979,
          caption: '"Many men go fishing all of their lives without knowing that it is not fish they are after.” - Henry David Thoreau',
          storyId: "0",
          path: "New/TheRidge",
          firstImg: "ridge1",
          lastImg: "ridge2",
        }
      },
      {
        loc: "",
        lat: 47.7511,
        lng: -120.7401,
        size: 0.5,
        color: "white",
        description: {
          title: "Dogs",
          fullLoc: "Washington, USA",
          year: 2011,
          caption: '“Dogs are better than human beings because they know but do not tell.” - Emily Dickinson',
          storyId: "1",
          path: "New/Dogs",
          firstImg: "dogs2",
          lastImg: "dogs3",
        }
      },
      {
        loc: "",
        lat: 6.2476,
        lng: -75.5658,
        size: 0.2,
        color: "white",
        description: {
          title: "Half-Sleep",
          fullLoc: "Medellín, Colombia",
          year: 2007,
          caption: '“Let’s begin by taking a smallish nap or two…” - Winnie The Pooh',
          storyId: "2",
          path: "New/HalfSleep",
          firstImg: "sleep1",
          lastImg: "sleep4",
        }
      },
      {
        loc: "",
        lat: 35.7596,
        lng: -79.0193,
        size: 0.3,
        color: "rgba(255, 165, 0, 0.75)",
        description: {
          title: "Earbuds",
          fullLoc: "North Carolina, USA",
          year: 2015,
          caption: '“The why of murder always fascinates me so much more than the how.” - Ann Rule',
          storyId: "3",
          path: "New/Earbuds",
          firstImg: "earbuds1",
          lastImg: "earbuds3",
        }
      },
      {
        loc: "",
        lat: 49.136350,
        lng: 3.940368,
        size: 0.1,
        color: "white",
        description: {
          title: "Forever",
          fullLoc: "A Small Village, Eastern France",
          year: 1919,
          caption: '“Death may be the greatest of all human blessings.” - Socrates',
          storyId: "4",
          path: "Crescent/Forever",
          firstImg: "forever4",
          lastImg: "forever3",
        }
      },
      {
        loc: "",
        lat: 51.5072,
        lng: -0.1276,
        size: 0.1,
        color: "rgba(255, 165, 0, 0.75)",
        description: {
          title: "Just A Tad Off The Top",
          fullLoc: "London, UK",
          year: 2001,
          caption: '“We are always the same age inside.” - Gertrude Stein',
          storyId: "5",
          path: "Crescent/JustATadOffTheTop",
          firstImg: "tad1",
          lastImg: "tad3",
        }
      },
      {
        loc: "",
        lat: 42.4072,
        lng: -71.3824,
        size: 0.2,
        color: "white",
        description: {
          title: "Woodwalkers",
          fullLoc: "Massachusetts, USA",
          year: 1999,
          caption: '“We’re all ghosts. We all carry, inside us, people who came before us.” - Liam Callanan',
          storyId: "6",
          path: "Crescent/Woodwalkers",
          firstImg: "wood3",
          lastImg: "wood2",
        }
      },
      {
        loc: "",
        lat: 40.7128,
        lng: -74.0060,
        size: 0.1,
        color: "white",
        description: {
          title: "For You, It's Free",
          fullLoc: "New York City, USA",
          year: 2013,
          caption: '“I want to be a part of it: New York, New York” - Frank Sinatra',
          storyId: "7",
          path: "Crescent/ForYouItsFree",
          firstImg: "free3",
          lastImg: "free2",
        }
      },
      {
        loc: "",
        lat: 54.240905,
        lng: -114.951658,
        size: 0.2,
        color: "white",
        description: {
          title: "Lutgo Cave",
          fullLoc: "Alberta, Canada",
          year: 2002,
          caption: '“Caves are whimsical things.” - William Stone',
          storyId: "8",
          path: "Quarter/LutgoCave",
          firstImg: "cave2",
          lastImg: "cave3",
        }
      },
      {
        loc: "",
        lat: 60.197763,
        lng: 5.373208,
        size: 0.1,
        color: "white",
        description: {
          title: "Tickle",
          fullLoc: "Near Bergen, Norway",
          year: 1975,
          caption: '“This life is like a swimming pool. You dive into the water, but you can’t see how deep it is.” - Dennis Rodman',
          storyId: "9",
          path: "Quarter/Tickle",
          firstImg: "tickle2",
          lastImg: "tickle4",
        }
      },
      {
        loc: "",
        lat: -31.936706,
        lng: 115.754770,
        size: 0.1,
        color: "white",
        description: {
          title: "UV",
          fullLoc: "Perth, Australia",
          year: 1963,
          caption: '“In a thousand years archeologists will dig up tanning beds and think we fried people as punishment.” - Olivia Wilde',
          storyId: "10",
          path: "Quarter/UV",
          firstImg: "uv2",
          lastImg: "uv1",
        }
      },
      {
        loc: "",
        lat: -23.5558,
        lng: -46.6396,
        size: 0.3,
        color: "white",
        description: {
          title: "The Janitor Game",
          fullLoc: "São Paulo, Brazil",
          year: 1996,
          caption: '“A museum is a place where one should lose one’s head.” - Renzo Piano',
          storyId: "11",
          path: "Quarter/TheJanitorGame",
          firstImg: "janitor1",
          lastImg: "janitor2",
        }
      },
      {
        loc: "",
        lat: 38.597626,
        lng: -80.454903,
        size: 0.8,
        color: "white",
        description: {
          title: "Route 47",
          fullLoc: "West Virginia, USA",
          year: 1971,
          caption: '“The wheels on the bus go round and round, round and round, round and round.” - Verna Hills',
          storyId: "12",
          path: "Gibbous/Route47",
          firstImg: "route4",
          lastImg: "route5",
        }
      },
      {
        loc: "",
        lat: -29.8587,
        lng: 31.049999,
        size: 0.2,
        color: "white",
        description: {
          title: "Rated-R",
          fullLoc: "Durban, South Africa",
          year: 2019,
          caption: '“Always make the audience suffer as much as possible.” - Alfred Hitchcock',
          storyId: "13",
          path: "Gibbous/RatedR",
          firstImg: "rated3",
          lastImg: "rated2",
        }
      },
      {
        loc: "",
        lat: 46.8797,
        lng: -110.3626,
        size: 0.2,
        color: "white",
        description: {
          title: "Father's Day",
          fullLoc: "Montana, USA",
          year: 2020,
          caption: '“An almost perfect relationship with his father was the earthly root of all wisdom.” - C.S. Lewis',
          storyId: "14",
          path: "Gibbous/FathersDay",
          firstImg: "father2",
          lastImg: "father3",
        }
      },
      {
        loc: "",
        lat: 42.331429,
        lng: -83.045753,
        size: 0.7,
        color: "white",
        description: {
          title: "Ghosts In The Graveyard",
          fullLoc: "Michigan, USA",
          year: 2010,
          caption: '“Children have always learned and created places for themselves through play.” - Donna R. Barnes',
          storyId: "15",
          path: "Gibbous/GhostsInTheGraveyard",
          firstImg: "ghosts1",
          lastImg: "ghosts2",
        }
      },
      {
        loc: "",
        lat: 32.3182,
        lng: -86.9023,
        size: 0.6,
        color: "white",
        description: {
          title: "Local Z",
          fullLoc: "Alabama, USA",
          year: 2016,
          caption: '“College isn’t the place to go for ideas.” - Helen Keller',
          storyId: "16",
          path: "Full/LocalZ",
          firstImg: "localz2",
          lastImg: "localz1",
        }
      },
      {
        loc: "",
        lat: 51.1657,
        lng: 10.4515,
        size: 0.1,
        color: "rgba(255, 165, 0, 0.75)",
        description: {
          title: "Mimicry",
          fullLoc: "Unknown, Germany",
          year: 1965,
          caption: '“Extinction is the rule. Survival is the exception.” - Carl Sagan',
          storyId: "17",
          path: "Full/Mimicry",
          firstImg: "mimicry3",
          lastImg: "mimicry2",
        }
      },
      {
        loc: "",
        lat: 34.0522,
        lng: -118.2437,
        size: 0.8,
        color: "white",
        description: {
          title: "A Glass House and a Pebble",
          fullLoc: "California, USA",
          year: 2021,
          caption: '“The greatest gift of life is friendship, and I have received it.” - Hubert H. Humphrey',
          storyId: "18",
          path: "Full/AGlassHouseAndAPebble",
          firstImg: "house1",
          lastImg: "house2",
        }
      },
      {
        loc: "",
        lat: 35.6762,
        lng: 139.6503,
        size: 0.3,
        color: "white",
        description: {
          title: "A Smiling Moon",
          fullLoc: "Tokyo, Japan",
          year: 2041,
          caption: '“We ran as if to meet the moon.” - Robert Frost',
          storyId: "19",
          path: "Full/ASmilingMoon",
          firstImg: "moon1",
          lastImg: "moon2",
        }
      },
];

export default points;